### ISSUE TITLE
Rewrite: Bot throws errors and crashes

### ISSUE THREAD

**Issue by VolkerSchlegel** [passivity/emojis#10]
The Bot is throwing the same error over and over: "Failed to change presence: object NoneType can't be used in 'await' expression". 
It also crashed when I added it to a guild. Can't say if it was because of that or it just crashes at some point.

**Comment by Kakiking** [comment]
Oh, just realized... The API is throwing the error..﻿

**Comment by VolkerSchlegel** [comment]
It is caused by `await time.sleep(20)`...﻿

**Comment by VolkerSchlegel** [comment]
Simply removing `await` was enough.. I should fix this in master, too.﻿
