### ISSUE TITLE
Emoji approval queue not working

### ISSUE THREAD

**Issue by squeakerdev** [passivity/emojis#6]
Adding reactions on the emoji approval queue embeds doesn't always make it work. Will fix this later by replacing the reaction system with an `>approve` command.

**Comment by squeakerdev** [comment]
If anybody wants to contribute and add this command, here's what I plan for it: 

- When adding an emoji to the queue, a unique ID will be generated (message ID?) that will be added the the embed;
- The syntax will be `>approve [ID]` or `>reject [ID]`;
- Users will require `Manage Guild` to use it.

**Comment by squeakerdev** [comment]
I removed the emoji approval system because it's kind of useless and it ended up causing more issues than it ever solved.

**Comment by Max-Trueby** [comment]
Ok
