### ISSUE TITLE
Pinging bot does not display prefix 

### ISSUE THREAD

**Issue by squeakerdev** [passivity/emojis#7]
Not sure why this happens. Works sometimes but not other times.

**Comment by 3jm** [comment]
> Not sure why this happens. Works sometimes but not other times.

This is most likely a problem with the bot hosting service or just rate limits idk (just throwing 2 ideas)

**And yes i know this is from September 2020**

**Comment by squeakerdev** [comment]
I don't think it's an issue with rate limits or the hosting service. If that were the case, we'd have seen issues with other parts of the bot too (which we didn't, at time of writing).

**Comment by editid0** [comment]
is this still an issue, even with the current bot, it can probably be closed if not :p

**Comment by VolkerSchlegel** [comment]
I have no idea, I have never seen it occuring so it seems to be pretty rare at least 🤔

**Comment by squeakerdev** [comment]
Closed as issue may not be present.
